/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Kevin Maldonado
 */
public class Login_A extends javax.swing.JFrame {

    /**
     * Creates new form Login_A
     */
    public Login_A() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloA = new javax.swing.JLabel();
        lblUsuarioA = new javax.swing.JLabel();
        lblContraseñaA = new javax.swing.JLabel();
        txtUsuarioA = new javax.swing.JTextField();
        txtContraseñaA = new javax.swing.JTextField();
        btnIngresarA = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblFondoA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloA.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloA.setText("INICIO DE SESIÓN ADMINISTRADOR");
        getContentPane().add(lblTituloA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblUsuarioA.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUsuarioA.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioA.setText("Usuario:");
        getContentPane().add(lblUsuarioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblContraseñaA.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblContraseñaA.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseñaA.setText("Contraseña:");
        getContentPane().add(lblContraseñaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtUsuarioA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuarioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));
        getContentPane().add(txtContraseñaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 180, -1));

        btnIngresarA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/log_in.png"))); // NOI18N
        btnIngresarA.setText("Ingresar");
        btnIngresarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarAActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 140, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_undo.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 140, 40));

        lblFondoA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/13.jpg"))); // NOI18N
        getContentPane().add(lblFondoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.dispose();
        Menu mn = new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarAActionPerformed
        // TODO add your handling code here:
        REmpleado e = new  REmpleado();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarAActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblContraseñaA;
    private javax.swing.JLabel lblFondoA;
    private javax.swing.JLabel lblTituloA;
    private javax.swing.JLabel lblUsuarioA;
    private javax.swing.JTextField txtContraseñaA;
    private javax.swing.JTextField txtUsuarioA;
    // End of variables declaration//GEN-END:variables
}
