/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Kevin Maldonado
 */
public class Login_E extends javax.swing.JFrame {

    /**
     * Creates new form Login_E
     */
    public Login_E() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloE = new javax.swing.JLabel();
        lblUsuarioE = new javax.swing.JLabel();
        lblContraseñaE = new javax.swing.JLabel();
        txtUsuarioE = new javax.swing.JTextField();
        txtContraseñaE = new javax.swing.JTextField();
        btnIngresarE = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblFondoE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloE.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloE.setText("INICIO DE SESIÓN EMPLEADO");
        getContentPane().add(lblTituloE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        lblUsuarioE.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblUsuarioE.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioE.setText("Usuario:");
        getContentPane().add(lblUsuarioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        lblContraseñaE.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblContraseñaE.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseñaE.setText("Contraseña:");
        getContentPane().add(lblContraseñaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txtUsuarioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioEActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuarioE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));
        getContentPane().add(txtContraseñaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, -1));

        btnIngresarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/log_in.png"))); // NOI18N
        btnIngresarE.setText("Ingresar");
        btnIngresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 140, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_undo.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 140, 40));

        lblFondoE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/13.jpg"))); // NOI18N
        getContentPane().add(lblFondoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Menu mn=new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEActionPerformed
        // TODO add your handling code here:
        RCliente c = new RCliente();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarEActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblContraseñaE;
    private javax.swing.JLabel lblFondoE;
    private javax.swing.JLabel lblTituloE;
    private javax.swing.JLabel lblUsuarioE;
    private javax.swing.JTextField txtContraseñaE;
    private javax.swing.JTextField txtUsuarioE;
    // End of variables declaration//GEN-END:variables
}
