/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ConexionPG.PgConect;
import Validaciones.Val;
import entidades.Cliente;
import entidades.Puesto;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class VPuesto extends javax.swing.JFrame {

    public static List<Puesto> listaPuesto = new ArrayList();

    /**
     * Creates new form VPuesto
     */
    public VPuesto() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            tblModelo();
        } catch (SQLException ex) {
            Logger.getLogger(Puesto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblvrfEstado = new javax.swing.JLabel();
        lbl_VTipo = new javax.swing.JLabel();
        btn_Reegresar = new javax.swing.JButton();
        btn_Buscar = new javax.swing.JButton();
        btn_Modificar = new javax.swing.JButton();
        btn_Registrar = new javax.swing.JButton();
        btn_mostrar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Limpiar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPuestos = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 77, 103));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PUESTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, 25));

        jLabel3.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo de Puesto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        lblvrfEstado.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblvrfEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 170, 20));

        lbl_VTipo.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lbl_VTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 245, 16));

        btn_Reegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btn_Reegresar.setText("Salir");
        btn_Reegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Reegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 17, 100, -1));

        btn_Buscar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Buscar.png"))); // NOI18N
        btn_Buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 60, 50));

        btn_Modificar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Modificar.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        btn_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoEditar.png"))); // NOI18N
        btn_Modificar.setText("Modificar");
        btn_Modificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, 52));

        btn_Registrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Registrar.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        btn_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoGuardar.png"))); // NOI18N
        btn_Registrar.setText("Ingresa");
        btn_Registrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 134, 51));

        btn_mostrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_mostrar.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        btn_mostrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoMostrar.png"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 130, -1));

        btn_Eliminar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Eliminar.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoBorrar.png"))); // NOI18N
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 130, 52));

        btn_Limpiar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Limpiar.setFont(new java.awt.Font("Cascadia Code", 1, 12)); // NOI18N
        btn_Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLimpiar.png"))); // NOI18N
        btn_Limpiar.setText("Limpiar");
        btn_Limpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 130, 52));

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Automovil-camioneta", "Moto", "Camion" }));
        jPanel1.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 230, -1));

        tblPuestos.setBackground(new java.awt.Color(102, 102, 102));
        tblPuestos.setForeground(new java.awt.Color(255, 255, 255));
        tblPuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPuesto", "Tipo_Puesto", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPuestos.setColumnSelectionAllowed(true);
        tblPuestos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblPuestosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblPuestosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblPuestos);
        tblPuestos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblPuestos.getColumnModel().getColumnCount() > 0) {
            tblPuestos.getColumnModel().getColumn(0).setResizable(false);
            tblPuestos.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 780, 120));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/12.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_ReegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReegresarActionPerformed
        // TODO add your handling code here:
        Menu m = new Menu();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ReegresarActionPerformed

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        PgConect conect = new PgConect();
        Puesto puest;
        if (cmbTipo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "seleccione un tipo");
        } else {

            puest = new Puesto(cmbTipo.getSelectedItem().toString());
            try {
                if (!conect.pkPuesto(puest.getIdpuesto())) {
                    conect.insPuesto(puest.getIdpuesto(), puest.getTipo(), puest.getOcupado());
                    JOptionPane.showMessageDialog(rootPane, "Puesto guardado");
                    tblModelo();
                    
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "registro existente");
                }
            } catch (SQLException ex) {
                Logger.getLogger(VPuesto.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    private void tblPuestosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPuestosKeyTyped

    }//GEN-LAST:event_tblPuestosKeyTyped

    private void tblPuestosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPuestosKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String idpuesto = tblPuestos.getValueAt(tblPuestos.getSelectedRow(), 0).toString();
            String tipo = tblPuestos.getValueAt(tblPuestos.getSelectedRow(), 1).toString();
            boolean estado = (Boolean) tblPuestos.getValueAt(tblPuestos.getSelectedRow(), 2);

            PgConect con = new PgConect();
            con.modificarPuesto(tipo, estado);
        }
    }//GEN-LAST:event_tblPuestosKeyReleased

    public void limpiar() {
     cmbTipo.setSelectedIndex(0);

    }

    public void tblModelo() throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel();
        tblPuestos.setModel(modelo);
        PgConect con = new PgConect();
        ResultSet puesto = con.mostrarPuest();
        ResultSetMetaData rsmd = puesto.getMetaData();
        int columns = rsmd.getColumnCount();

        modelo.addColumn("idpuesto");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estado");

        while (puesto.next()) {
            Object[] filas = new Object[columns];
            for (int i = 0; i < columns; i++) {
                filas[i] = puesto.getObject(i + 1);
            }
            modelo.addRow(filas);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Limpiar;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Reegresar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lbl_VTipo;
    private javax.swing.JLabel lblvrfEstado;
    private javax.swing.JTable tblPuestos;
    // End of variables declaration//GEN-END:variables
}
