/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ConexionPG.PgConect;
import Validaciones.Val;
import entidades.DetalleReserva;
import entidades.Puesto;
import entidades.Reserva;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Usuario
 */
public class VReserva extends javax.swing.JFrame {

    String idempleado;
    String idalquiler;

    /**
     * Creates new form VReserva
     */
    public VReserva(String idalquiler, String idempleado) {
        initComponents();
        setLocationRelativeTo(null);
        this.idalquiler = idalquiler;
        this.idempleado = idempleado;
        try {
            buscar(" ");
        } catch (SQLException ex) {
            Logger.getLogger(VReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public VReserva(String idempleado) {
        initComponents();
        setLocationRelativeTo(null);
        this.idempleado = idempleado;
        try {
            buscar(" ");
        } catch (SQLException ex) {
            Logger.getLogger(VReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public VReserva(){
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReserva = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        fechaIngreso = new com.toedter.calendar.JDateChooser();
        fechaSalida = new com.toedter.calendar.JDateChooser();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblVfyCedula = new javax.swing.JLabel();
        txtCostoR = new javax.swing.JTextField();
        txtPlacaR = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarP = new javax.swing.JButton();
        lblPlacaR = new javax.swing.JLabel();
        lblIDPuestoR = new javax.swing.JLabel();
        lblCostoR = new javax.swing.JLabel();
        lblVfyPlacaR = new javax.swing.JLabel();
        cmbPuestoR = new javax.swing.JComboBox<>();
        lblFondoP = new javax.swing.JLabel();
        txtFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cascadia Code", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡REGISTRAR ALQUILER!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/find.png"))); // NOI18N
        jLabel6.setText("Busqueda");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 140, -1));

        txtBuscarA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarAKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 490, -1));

        tblReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblReserva);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 900, 160));

        jLabel8.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha Salida: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, 20));

        jLabel7.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha Ingreso:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 20));

        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 200, -1));
        getContentPane().add(fechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 200, 30));
        getContentPane().add(fechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 200, 30));

        btnRegistrar.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoGuardar.png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 170, -1));

        btnLimpiar.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoLimpiar.png"))); // NOI18N
        btnLimpiar.setText("CANCELAR");
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 600, 170, -1));

        btnEliminar.setFont(new java.awt.Font("Cascadia Code", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoBorrar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 180, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btnSalir.setText("SALIR");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 30));

        lblVfyCedula.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblVfyCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 180, 10));
        getContentPane().add(txtCostoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 160, -1));

        txtPlacaR.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPlacaRFocusLost(evt);
            }
        });
        getContentPane().add(txtPlacaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 160, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarP.setText("+");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 40, 40));

        lblPlacaR.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblPlacaR.setText("Placa:");
        jPanel1.add(lblPlacaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        lblIDPuestoR.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblIDPuestoR.setText("ID Puesto:");
        jPanel1.add(lblIDPuestoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblCostoR.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblCostoR.setText("Costo:");
        jPanel1.add(lblCostoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jPanel1.add(lblVfyPlacaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 160, 10));

        jPanel1.add(cmbPuestoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 160, -1));
        jPanel1.add(lblFondoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 460, 210));

        txtFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reserva.png"))); // NOI18N
        getContentPane().add(txtFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        if (Val.digVfy(txtCedula.getText())) {
            PgConect con = new PgConect();
            ResultSet exisCli = con.pkCedCli(txtCedula.getText());
            try {
                if (!exisCli.next()) {
                    JOptionPane.showMessageDialog(rootPane, "Debe registrar al cliente");
                    RCliente cli = new RCliente(txtCedula.getText());
                    cli.setVisible(true);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CTicketIngreso.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lblVfyCedula.setText("No es una cedula");
        }
    }//GEN-LAST:event_txtCedulaFocusLost

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        RDetalle();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtBuscarAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarAKeyReleased
        try {
            buscar(txtBuscarA.getText());
        } catch (SQLException ex) {
            Logger.getLogger(VReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscarAKeyReleased

    private void txtPlacaRFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPlacaRFocusLost
        if (Val.placa(txtPlacaR.getText())) {
            try {
                PgConect con = new PgConect();
                ResultSet relacion = con.owner(txtCedula.getText(), txtPlacaR.getText());
                ResultSet idcliente = con.pkCedCli(txtCedula.getText());
                if (relacion.next()) {
                    cbxModel(txtPlacaR.getText());
                } else {
                    if (con.pkVehiculo(txtPlacaR.getText()).next()) {
                        con.insDuenio(txtCedula.getText(), txtPlacaR.getText());
                        cbxModel(txtPlacaR.getText());
                    } else {
                        idcliente.next();
                        RVehiculo veh = new RVehiculo(idcliente.getString("idcliente"), 
                        txtPlacaR.getText());
                        veh.setVisible(true);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(CTicketIngreso.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            lblVfyPlacaR.setText("No es una placa");
        }
    }//GEN-LAST:event_txtPlacaRFocusLost

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        try {
            PgConect conect = new PgConect();
            Puesto puesto = (Puesto) this.cmbPuestoR.getSelectedItem();
            DetalleReserva dr = new DetalleReserva(txtPlacaR.getText(), puesto.getIdpuesto(), 0);
            ResultSet idcliente = conect.pkCedCli(txtCedula.getText());
            if(idcliente.next()){
                conect.insDetR(dr.getIddetalle(), idalquiler, idcliente.getString("idcliente"), dr.getPuesto(), 0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VReserva.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_btnAgregarPActionPerformed

    public void limpiar() {
        txtCedula.setText(null);
        fechaIngreso.setDate(null);
        fechaSalida.setDate(null);
    }
    
    public void RDetalle(){
        PgConect conect = new PgConect();

        try {
            if (!Val.digVfy(txtCedula.getText())) {
                JOptionPane.showMessageDialog(null, "Datos incorrectos");
            } else {
                ResultSet idcli = conect.pkCedCli(txtCedula.getText());
                if (idcli.next()) {
                    Reserva rv = new Reserva(idcli.getString("idcliente"), idempleado, fechaIngreso.getDate(), fechaSalida.getDate());
                    long form = fechaIngreso.getDate().getTime();
                    java.sql.Date time = new java.sql.Date(form);
                    long form2 = fechaSalida.getDate().getTime();
                    java.sql.Date time2 = new java.sql.Date(form2);
                    conect.insRva(rv.getIdAlquiler(),rv.getIdcliente(), rv.getIdempleado(), time, time2);
                    String idalquiler = rv.getIdAlquiler();
                    JOptionPane.showMessageDialog(rootPane, "Alquiler guardado");
                    buscar(" ");
                    limpiar();   
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(RVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void cbxModel(String placa) {
        try {
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            PgConect con = new PgConect();
            cmbPuestoR.setModel(model);
            ResultSet places = con.cbxPuestos(placa);
            
            while(places.next()) {
                model.addElement(new Puesto(places.getShort(1), places.getShort(2), places.getBoolean(3)));
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(VReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }

    public void buscar(String idpersona) throws SQLException {
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 3 || column == 4) {
                    return true;
                } else {
                    return false;
                }
            }
        };
        PgConect conec = new PgConect();
        Connection conectar = conec.Conectar();

        modelo.addColumn("ID Alquiler");
        modelo.addColumn("Cédula");
        modelo.addColumn("ID Empleado");
        modelo.addColumn("F.Ingreso");
        modelo.addColumn("F.Salida");
        //modelo.addColumn("Placa");
        //modelo.addColumn("ID Puesto");
        //modelo.addColumn("Costo");

        tblReserva.setModel(modelo);
        String sql = " ";
        if (idpersona.equals(" ")) {
            sql = "SELECT idalquiler, clientes.idpersona, empleados.idempleado, fechaing, fechasal "
                    + "FROM alquileres, clientes, empleados "
                    + "WHERE clientes.idcliente = alquileres.idcliente "
                    + "AND empleados.idempleado = alquileres.idempleado;";
        } else {
            sql = "SELECT idalquiler, clientes.idpersona, empleados.idempleado, fechaing, fechasal "
                    + "FROM alquileres, clientes, empleados "
                    + "WHERE clientes.idcliente = alquileres.idcliente "
                    + "AND empleados.idempleado = alquileres.idempleado AND idpersona like '%" + idpersona + "%';";;

        }
        String Usuarios[] = new String[5];
        Statement set;
        try {
            set = conectar.createStatement();
            ResultSet resul = set.executeQuery(sql);
            while (resul.next()) {
                Usuarios[0] = resul.getString(1);
                Usuarios[1] = resul.getString(2);
                Usuarios[2] = resul.getString(3);
                Usuarios[3] = resul.getString(4);
                Usuarios[4] = resul.getString(5);
                //Usuarios[5] = resul.getString(6);
                //Usuarios[6] = resul.getString(7);
                //Usuarios[7] = resul.getString(8);
                modelo.addRow(Usuarios);

            }
            tblReserva.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(RCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbPuestoR;
    private com.toedter.calendar.JDateChooser fechaIngreso;
    private com.toedter.calendar.JDateChooser fechaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCostoR;
    private javax.swing.JLabel lblFondoP;
    private javax.swing.JLabel lblIDPuestoR;
    private javax.swing.JLabel lblPlacaR;
    private javax.swing.JLabel lblVfyCedula;
    private javax.swing.JLabel lblVfyPlacaR;
    private javax.swing.JTable tblReserva;
    private javax.swing.JTextField txtBuscarA;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCostoR;
    private javax.swing.JLabel txtFondo;
    private javax.swing.JTextField txtPlacaR;
    // End of variables declaration//GEN-END:variables
}
